"""Reopen, inspect and render the authored source without exporting or resaving it.

Run with Blender's --background --factory-startup --python option. All inspection
changes are temporary and are confined to the newly opened source in this process.
The JSON records generated images separately from a human/agent visual review.
"""
import json
import math
from pathlib import Path

import bpy
import bmesh
from mathutils import Vector
from bpy_extras.object_utils import world_to_camera_view

ROOT = Path(__file__).resolve().parents[3]
ART = ROOT / 'ArtSource/Blender/SpaceEnvironment'
DEST = ART / 'SpaceEnvironment.blend'
PREVIEWS = ART / 'Previews'


def mesh_statistics(mesh, inward=False):
    """Check topology and orientation per connected closed component."""
    mesh.calc_loop_triangles()
    bm = bmesh.new()
    bm.from_mesh(mesh)
    bm.verts.ensure_lookup_table()
    bm.faces.ensure_lookup_table()
    components = []
    unseen = set(bm.verts)
    while unseen:
        first = unseen.pop()
        found = {first}
        todo = [first]
        while todo:
            v = todo.pop()
            for edge in v.link_edges:
                other = edge.other_vert(v)
                if other in unseen:
                    unseen.remove(other)
                    found.add(other)
                    todo.append(other)
        faces = set(f for v in found for f in v.link_faces)
        # Shift to a nearby origin to keep the volume calculation stable for the
        # deliberately separated, off-origin rocks in the far-sector meshes.
        center = sum((v.co for v in found), Vector()) / len(found)
        volume = 0.0
        for face in faces:
            a = face.verts[0].co - center
            for i in range(1, len(face.verts) - 1):
                b = face.verts[i].co - center
                c = face.verts[i + 1].co - center
                volume += a.dot(b.cross(c)) / 6.0
        components.append({
            'vertices': sorted(v.index for v in found),
            'signed_volume': volume,
            'local_center': list(center),
            'local_radius': max((v.co - center).length for v in found),
        })
    result = {
        'mesh': mesh.name,
        'vertices': len(mesh.vertices),
        'triangles': len(mesh.loop_triangles),
        'components': len(components),
        'non_manifold_edges': sum(not e.is_manifold for e in bm.edges),
        'inconsistent_face_orientation_edges': sum(
            e.is_manifold and not e.is_contiguous for e in bm.edges),
        'degenerate_faces': sum(f.calc_area() < 1e-12 for f in bm.faces),
        'non_finite_vertices': sum(
            not all(math.isfinite(x) for x in v.co) for v in bm.verts),
        'invalid_normals': sum(
            not all(math.isfinite(x) for x in p.normal) or p.normal.length < .99
            for p in mesh.polygons),
        'signed_volume': sum(c['signed_volume'] for c in components),
        'minimum_abs_component_volume': min(
            (abs(c['signed_volume']) for c in components), default=0),
        'orientation': 'inward sky shell' if inward else 'outward closed surfaces',
        'component_orientation_valid': all(
            c['signed_volume'] < -1e-10 if inward else c['signed_volume'] > 1e-10
            for c in components),
        'uv_layers': len(mesh.uv_layers),
    }
    bm.free()
    return result, components


def sphere_clearance(obj, components, center, reserve_radius):
    """Conservative sphere containment for every connected solid component."""
    best = float('inf')
    for comp in components:
        verts = [obj.matrix_world @ obj.data.vertices[i].co
                 for i in comp['vertices']]
        pivot = sum(verts, Vector()) / len(verts)
        radius = max((v - pivot).length for v in verts)
        best = min(best, (pivot - center).length - radius - reserve_radius)
    return best


def project_bounds(scene, camera, obj):
    points = [world_to_camera_view(scene, camera, obj.matrix_world @ v.co)
              for v in obj.data.vertices]
    return {
        'center_top_left': [
            (min(p.x for p in points) + max(p.x for p in points)) / 2,
            1 - (min(p.y for p in points) + max(p.y for p in points)) / 2],
        'height_fraction': max(p.y for p in points) - min(p.y for p in points),
        'width_fraction': max(p.x for p in points) - min(p.x for p in points),
        'minimum_camera_depth': min(p.z for p in points),
    }


def main():
    PREVIEWS.mkdir(parents=True, exist_ok=True)
    report = {
        'blender_version': bpy.app.version_string,
        'source': str(DEST.relative_to(ROOT)),
        'source_reopened': False,
        'errors': [], 'warnings': [], 'checks': {}, 'images': [],
        'visual_review': 'Images generated by this script; visual acceptance is recorded separately by the reviewer.',
    }

    def check(key, condition, description):
        report['checks'][key] = {'passed': bool(condition), 'description': description}
        if not condition:
            report['errors'].append(key + ': ' + description)

    bpy.ops.wm.open_mainfile(filepath=str(DEST))
    report['source_reopened'] = True
    scene = bpy.data.scenes.get('SpaceEnvironment')
    if scene is None:
        raise RuntimeError('Saved source lacks SpaceEnvironment scene')
    if bpy.context.window:
        bpy.context.window.scene = scene
    bpy.context.view_layer.update()
    cfg = json.loads(scene['config_json'])
    external_cfg = json.loads((ROOT / 'Tools/Blender/SpaceEnvironment/config.json').read_text(encoding='utf-8'))
    summary = json.loads((ART / 'source_layout_summary.json').read_text(encoding='utf-8'))
    check('config_saved', cfg == external_cfg == summary['config'], 'Packed scene configuration equals generation configuration and source summary.')
    check('owned_scene', scene.get('owner') == 'DropletPrototype.SpaceEnvironment.v1', 'Scene has the explicit environment ownership marker.')
    required_collections = ['CelestialBodies', 'AsteroidLibrary', 'CelestialLibrary',
        'AsteroidBelt_Near', 'AsteroidBelt_Mid', 'AsteroidBelt_Far',
        'GameplayReserve', 'ReferenceCameras', 'PreviewOnly', 'LayoutMarkers']
    check('collections', all(bpy.data.collections.get(n) for n in required_collections), 'Required editable source collections exist.')
    library = [o for n in ['AsteroidLibrary', 'CelestialLibrary']
               for o in bpy.data.collections[n].objects if o.type == 'MESH']
    check('library_hidden_from_main', all(
        scene.view_layers[0].layer_collection.children[n].exclude
        for n in ['AsteroidLibrary', 'CelestialLibrary', 'LayoutMarkers']),
        'Prototype-only libraries and export marker collection are excluded from main rendering.')
    check('library_no_modifiers', all(len(o.modifiers) == 0 for o in library), 'All export meshes have applied geometry and no unresolved modifiers.')
    check('library_unit_transform', all(
        o.location.length < 1e-6 and o.rotation_euler.to_matrix().is_identity
        and (o.scale - Vector((1, 1, 1))).length < 1e-6 for o in library),
        'Prototype transforms are centered at the intended export pivot with identity rotation and unit scale.')
    by_key = {(str(o.get('assetId')), int(o.get('lod', -1))): o for o in library}
    check('prototype_keys_unique', len(by_key) == len(library), 'Each (assetId, LOD) identifies exactly one prototype.')
    check('eight_rock_three_lods', all((f'Rock{i:02d}', j) in by_key
        for i in range(1, 9) for j in range(3)), 'Eight independent rock silhouettes each retain three authored LODs.')
    check('celestial_lods', ('Sun', 0) in by_key and all(('Earth', i) in by_key for i in range(3)), 'Sun and all three Earth LODs exist.')
    unique = {}
    components = {}
    for (aid, lod), obj in sorted(by_key.items()):
        stat, comp = mesh_statistics(obj.data, inward=aid == 'Sky')
        stat.update(assetId=aid, lod=lod)
        unique[obj.data.as_pointer()] = stat
        components[obj.data.as_pointer()] = comp
        valid = (stat['non_manifold_edges'] == 0 and
                 stat['inconsistent_face_orientation_edges'] == 0 and
                 stat['degenerate_faces'] == 0 and stat['non_finite_vertices'] == 0 and
                 stat['invalid_normals'] == 0 and stat['component_orientation_valid'])
        check('geometry_' + aid + '_LOD' + str(lod), valid,
              'Closed manifold mesh, finite outward normals and positive component volumes (sky intentionally inward).')
        if aid in ['Sun', 'Earth', 'Sky']:
            check('uv_' + aid + '_LOD' + str(lod), stat['uv_layers'] > 0, 'Texturable spherical asset retains UVs.')
    report['unique_export_meshes'] = list(unique.values())
    report['unique_mesh_count'] = len(unique)
    report['unique_triangles_all_lods'] = sum(s['triangles'] for s in unique.values())
    report['far_unique_triangles'] = sum(s['triangles'] for s in unique.values() if s['assetId'].startswith('Far'))
    check('unique_mesh_budget', report['unique_triangles_all_lods'] <= 60000, 'All unique prototype/LOD/far/sky triangles fit 60000.')
    check('far_mesh_budget', report['far_unique_triangles'] <= 15000, 'Combined far-sector geometry fits 15000 triangles.')
    check('sun_mesh_budget', 1000 <= len(by_key[('Sun', 0)].data.loop_triangles) <= 2000,
          'The smooth sun sphere fits the 1000-2000 triangle starting budget.')
    for i in range(1, 9):
        tris = [len(by_key[(f'Rock{i:02d}', j)].data.loop_triangles) for j in range(3)]
        check('lod_budget_Rock' + str(i),
              800 <= tris[0] <= 2000 and 200 <= tris[1] <= 500 and 40 <= tris[2] <= 120,
              'Rock triangle counts LOD0/1/2 = ' + str(tris))
    check('earth_lod_budget', len(by_key[('Earth', 0)].data.loop_triangles) <= 8000 and
          len(by_key[('Earth', 1)].data.loop_triangles) <= 2000 and
          len(by_key[('Earth', 2)].data.loop_triangles) <= 600,
          'Earth LOD triangle upper bounds 8000/2000/600.')

    instances = [o for o in scene.objects if o.type == 'MESH' and o.name.startswith('ENV_')]
    ids = [str(o.get('instanceId')) for o in instances]
    check('instance_ids', len(ids) == len(set(ids)) and 'None' not in ids, 'Every saved environment instance has a unique stable ID.')
    counts = {n: sum(o in instances for o in bpy.data.collections[n].objects)
              for n in ['CelestialBodies', 'AsteroidBelt_Near', 'AsteroidBelt_Mid', 'AsteroidBelt_Far', 'SkyBackground']}
    report['instance_counts'] = counts
    report['instance_total'] = len(instances)
    report['unique_meshes_referenced_by_visible_instances'] = len({o.data.as_pointer() for o in instances})
    report['per_instance_unique_mesh_copies'] = sum(o.data.as_pointer() not in unique for o in instances)
    check('instance_counts', counts['CelestialBodies'] == 2 and
          counts['AsteroidBelt_Near'] == cfg['near_count'] and
          counts['AsteroidBelt_Mid'] == cfg['mid_count'] and
          counts['AsteroidBelt_Far'] == cfg['far_sectors'] and counts['SkyBackground'] == 1,
          'Saved visible object counts agree with configured populations.')
    check('instances_share_prototype_mesh', all(o.data.as_pointer() in unique for o in instances), 'Every placement references existing prototype mesh data; zero per-instance mesh copies.')
    check('no_instance_modifiers', all(not o.modifiers for o in instances), 'No live per-instance geometry modifiers.')
    check('positive_instance_scales', all(min(o.scale) > 0 for o in instances), 'All placement scales are positive.')
    check('single_lod_per_blender_instance', all(sum(i == uid for i in ids) == 1 for uid in ids), 'Only one preview LOD is displayed at each stable placement.')
    marker_ids = [str(o.get('instanceId')) for o in bpy.data.collections['LayoutMarkers'].objects]
    check('marker_instance_correspondence', sorted(ids) == sorted(marker_ids), 'Layout marker IDs correspond one-to-one with scene instances.')

    center = Vector((cfg['gameplay_center'][0], cfg['gameplay_center'][2], cfg['gameplay_center'][1]))
    clearances = []
    for o in instances:
        if o.get('assetId') == 'Sky':
            continue  # An enclosing backdrop shell intentionally contains the reserve.
        clearances.append({'instanceId': o['instanceId'], 'assetId': o['assetId'],
            'conservative_min_clearance': sphere_clearance(o, components[o.data.as_pointer()], center, cfg['reserve_radius'])})
    report['clearances'] = clearances
    report['minimum_clearance'] = min(c['conservative_min_clearance'] for c in clearances)
    check('reserve_clear', report['minimum_clearance'] > 0,
          f"Each celestial/rock component lies outside the full {cfg['reserve_radius']}-unit reserve after including its bounding radius.")
    check('source_summary_clearance', all(r['clearance'] > 0 for r in summary['instances']), 'Generation-side source layout summary also reports positive clearance.')
    check('source_summary_ids', set(ids) == {r['id'] for r in summary['instances']} | {'Sky'}, 'Saved instance IDs agree with the source layout summary, plus the enclosing sky.')

    materials = {s.material.as_pointer(): s.material for o in instances for s in o.material_slots if s.material}
    report['material_count'] = len(materials)
    report['materials'] = sorted(m.name for m in materials.values())
    check('material_budget', len(materials) <= 6, 'Shared base-material count is at most six.')
    images = {}
    for mat in materials.values():
        if mat.use_nodes:
            for node in mat.node_tree.nodes:
                if node.type == 'TEX_IMAGE' and node.image:
                    images[node.image.as_pointer()] = node.image
    report['textures'] = []
    for im in images.values():
        exists = bool(im.filepath) and Path(bpy.path.abspath(im.filepath)).exists()
        entry = {'name': im.name, 'dimensions': list(im.size),
                 'packed': bool(im.packed_file), 'external_exists': exists,
                 'source': im.source, 'filepath': im.filepath}
        report['textures'].append(entry)
        check('image_reference_' + im.name, bool(im.packed_file) and exists and min(im.size) > 0,
              'Texture is both packed into the reopened source and present as an explicit external file.')
        check('image_budget_' + im.name, im.size[0] <= 2048 and im.size[1] <= 1024, 'Base texture stays within the 2048x1024 ceiling.')
    check('no_lights', not any(o.type == 'LIGHT' for o in scene.objects), 'Full environment source contains no formal lights.')
    check('neutral_workbench', scene.render.engine == 'BLENDER_WORKBENCH', 'Neutral Workbench preview is configured.')
    report['reference_projection'] = {
        str(o['assetId']): project_bounds(scene, bpy.data.objects['ReferenceCamera'], o)
        for o in instances if o.get('assetId') in ['Sun', 'Earth']}
    for aid in ['Sun', 'Earth']:
        actual = report['reference_projection'][aid]
        expected = cfg[aid.lower() + '_screen']
        check('reference_projection_' + aid,
              abs(actual['center_top_left'][0] - expected[0]) < .03 and
              abs(actual['center_top_left'][1] - expected[1]) < .03 and
              abs(actual['height_fraction'] - expected[2]) < .04,
              'Saved camera preserves intended screen position and angular size; measured mesh projection recorded.')

    def render(scene_to_render, camera, stem, hide_sky=False):
        sky = bpy.data.objects.get('ENV_Sky_Sky')
        old_camera = scene_to_render.camera
        sky_hidden = sky.hide_render if sky else False
        try:
            scene_to_render.camera = camera
            # Orthographic topology checks view the full belt from outside the
            # backdrop; omit only the enclosing sky shell in these previews.
            if sky and hide_sky:
                sky.hide_render = True
            scene_to_render.render.image_settings.file_format = 'PNG'
            scene_to_render.render.filepath = str(PREVIEWS / (stem + '.png'))
            bpy.ops.render.render(write_still=True, scene=scene_to_render.name)
            report['images'].append({'path': str((PREVIEWS / (stem + '.png')).relative_to(ROOT)),
                'camera': camera.name, 'sky_hidden_for_topology_view': hide_sky,
                'generated': True, 'visually_reviewed_by_script': False})
        finally:
            scene_to_render.camera = old_camera
            if sky:
                sky.hide_render = sky_hidden

    for name in ['ReferenceCamera', 'SideCamera', 'TopCamera', 'GameplayTurnCamera', 'BeltCloseCamera']:
        try:
            render(scene, bpy.data.objects[name], name, hide_sky=name in ['SideCamera', 'TopCamera'])
        except Exception as exc:
            report['errors'].append('Render ' + name + ': ' + repr(exc))
    showcase = bpy.data.scenes.get('AsteroidLibraryReview')
    if showcase and showcase.camera:
        try:
            render(showcase, showcase.camera, 'AsteroidLibraryReview')
            modifications = []
            try:
                for o in showcase.objects:
                    if o.type != 'MESH':
                        continue
                    mod = o.modifiers.new('TEMP_InspectionWireframe', 'WIREFRAME')
                    mod.thickness = .007
                    mod.use_replace = True
                    mod.use_even_offset = True
                    modifications.append((o, mod))
                render(showcase, showcase.camera, 'AsteroidLibraryWireframe')
            finally:
                for o, mod in modifications:
                    o.modifiers.remove(mod)
        except Exception as exc:
            report['errors'].append('Library render: ' + repr(exc))
    else:
        report['errors'].append('Missing AsteroidLibraryReview scene or camera.')
    report['source_resaved_by_inspector'] = False
    report['passed_automated_selfcheck'] = not report['errors']
    (ART / 'blender_selfcheck.json').write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding='utf-8')
    print('BLENDER_ENVIRONMENT_SELFCHECK', report['passed_automated_selfcheck'],
          'unique_meshes', report['unique_mesh_count'], 'triangles', report['unique_triangles_all_lods'],
          'instances', report['instance_total'], 'images_generated', len(report['images']))
    for error in report['errors']:
        print('SELFCHECK_ERROR', error)
    if report['errors']:
        raise RuntimeError('Environment automated source check failed; inspect blender_selfcheck.json before export.')


if __name__ == '__main__':
    main()
